# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TravelMainWindow(object):
    def setupUi(self, TravelMainWindow):
        TravelMainWindow.setObjectName("TravelMainWindow")
        TravelMainWindow.resize(644, 802)
        TravelMainWindow.setMinimumSize(QtCore.QSize(600, 800))
        TravelMainWindow.setStyleSheet("")
        self.Centralwidget = QtWidgets.QWidget(TravelMainWindow)
        self.Centralwidget.setStyleSheet("brgbackground-color:rgb(255, 255, 255)")
        self.Centralwidget.setObjectName("Centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.Centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.TitleLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout.addWidget(self.TitleLabel)
        spacerItem1 = QtWidgets.QSpacerItem(192, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(self.Centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.new_page = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.new_page.setFont(font)
        self.new_page.setObjectName("new_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.new_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.new_page)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nickname1 = QtWidgets.QLabel(self.widget_2)
        self.nickname1.setEnabled(False)
        self.nickname1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.nickname1.setFont(font)
        self.nickname1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nickname1.setTextFormat(QtCore.Qt.AutoText)
        self.nickname1.setIndent(10)
        self.nickname1.setObjectName("nickname1")
        self.horizontalLayout_2.addWidget(self.nickname1)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.day_set = QtWidgets.QSpinBox(self.widget_2)
        self.day_set.setObjectName("day_set")
        self.horizontalLayout_2.addWidget(self.day_set)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.time_set = QtWidgets.QSpinBox(self.widget_2)
        self.time_set.setMaximum(23)
        self.time_set.setObjectName("time_set")
        self.horizontalLayout_2.addWidget(self.time_set)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.settings = QtWidgets.QWidget(self.new_page)
        self.settings.setMinimumSize(QtCore.QSize(0, 80))
        self.settings.setObjectName("settings")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.settings)
        self.horizontalLayout_3.setContentsMargins(20, 8, 20, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.settings)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bullet = QtWidgets.QCheckBox(self.groupBox)
        self.bullet.setAutoExclusive(False)
        self.bullet.setObjectName("bullet")
        self.gridLayout_2.addWidget(self.bullet, 1, 1, 1, 1)
        self.train = QtWidgets.QCheckBox(self.groupBox)
        self.train.setCheckable(True)
        self.train.setChecked(False)
        self.train.setAutoRepeat(False)
        self.train.setAutoExclusive(False)
        self.train.setObjectName("train")
        self.gridLayout_2.addWidget(self.train, 1, 2, 1, 1)
        self.best_time = QtWidgets.QRadioButton(self.groupBox)
        self.best_time.setMinimumSize(QtCore.QSize(100, 0))
        self.best_time.setMaximumSize(QtCore.QSize(100, 16777215))
        self.best_time.setObjectName("best_time")
        self.Strategy = QtWidgets.QButtonGroup(TravelMainWindow)
        self.Strategy.setObjectName("Strategy")
        self.Strategy.addButton(self.best_time)
        self.gridLayout_2.addWidget(self.best_time, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 3, 1, 1)
        self.best_price = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.best_price.sizePolicy().hasHeightForWidth())
        self.best_price.setSizePolicy(sizePolicy)
        self.best_price.setMinimumSize(QtCore.QSize(100, 10))
        self.best_price.setMaximumSize(QtCore.QSize(100, 16777215))
        self.best_price.setObjectName("best_price")
        self.Strategy.addButton(self.best_price)
        self.gridLayout_2.addWidget(self.best_price, 0, 1, 1, 1)
        self.confirm_btn = QtWidgets.QPushButton(self.groupBox)
        self.confirm_btn.setMinimumSize(QtCore.QSize(50, 20))
        self.confirm_btn.setMaximumSize(QtCore.QSize(100, 30))
        self.confirm_btn.setObjectName("confirm_btn")
        self.gridLayout_2.addWidget(self.confirm_btn, 1, 4, 1, 1)
        self.three = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.three.sizePolicy().hasHeightForWidth())
        self.three.setSizePolicy(sizePolicy)
        self.three.setMinimumSize(QtCore.QSize(130, 10))
        self.three.setMaximumSize(QtCore.QSize(130, 16777215))
        self.three.setObjectName("three")
        self.Strategy.addButton(self.three)
        self.gridLayout_2.addWidget(self.three, 0, 2, 1, 1)
        self.air = QtWidgets.QCheckBox(self.groupBox)
        self.air.setAutoExclusive(False)
        self.air.setObjectName("air")
        self.gridLayout_2.addWidget(self.air, 1, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_3.addWidget(self.settings)
        self.editor = QtWidgets.QWidget(self.new_page)
        self.editor.setMinimumSize(QtCore.QSize(0, 110))
        self.editor.setMaximumSize(QtCore.QSize(16777215, 200))
        self.editor.setObjectName("editor")
        self.gridLayout = QtWidgets.QGridLayout(self.editor)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 5, 1, 1)
        self.Time_limit = QtWidgets.QSpinBox(self.editor)
        self.Time_limit.setMinimumSize(QtCore.QSize(50, 30))
        self.Time_limit.setMaximumSize(QtCore.QSize(100, 30))
        self.Time_limit.setMinimum(1)
        self.Time_limit.setMaximum(72)
        self.Time_limit.setObjectName("Time_limit")
        self.gridLayout.addWidget(self.Time_limit, 1, 6, 1, 1)
        self.time_lab = QtWidgets.QLabel(self.editor)
        self.time_lab.setObjectName("time_lab")
        self.gridLayout.addWidget(self.time_lab, 0, 6, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 1, 1, 1)
        self.TBox = QtWidgets.QComboBox(self.editor)
        self.TBox.setMinimumSize(QtCore.QSize(50, 30))
        self.TBox.setMaximumSize(QtCore.QSize(100, 30))
        self.TBox.setObjectName("TBox")
        self.TBox.addItem("")
        self.TBox.addItem("")
        self.TBox.addItem("")
        self.TBox.addItem("")
        self.TBox.addItem("")
        self.TBox.addItem("")
        self.TBox.addItem("")
        self.TBox.addItem("")
        self.TBox.addItem("")
        self.TBox.addItem("")
        self.gridLayout.addWidget(self.TBox, 1, 4, 1, 1)
        self.SBox = QtWidgets.QComboBox(self.editor)
        self.SBox.setMinimumSize(QtCore.QSize(100, 30))
        self.SBox.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.SBox.setFont(font)
        self.SBox.setObjectName("SBox")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.SBox.addItem("")
        self.gridLayout.addWidget(self.SBox, 1, 0, 1, 1)
        self.Add_btn = QtWidgets.QPushButton(self.editor)
        self.Add_btn.setMinimumSize(QtCore.QSize(100, 30))
        self.Add_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Add_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Add_btn.setObjectName("Add_btn")
        self.gridLayout.addWidget(self.Add_btn, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.editor)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.Start = QtWidgets.QLabel(self.editor)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Start.setFont(font)
        self.Start.setObjectName("Start")
        self.gridLayout.addWidget(self.Start, 0, 0, 1, 1)
        self.PBox = QtWidgets.QComboBox(self.editor)
        self.PBox.setMinimumSize(QtCore.QSize(100, 30))
        self.PBox.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.PBox.setFont(font)
        self.PBox.setCurrentText("北京")
        self.PBox.setObjectName("PBox")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.PBox.addItem("")
        self.gridLayout.addWidget(self.PBox, 1, 2, 1, 1)
        self.is_order = QtWidgets.QCheckBox(self.editor)
        self.is_order.setMinimumSize(QtCore.QSize(50, 30))
        self.is_order.setMaximumSize(QtCore.QSize(100, 30))
        self.is_order.setChecked(True)
        self.is_order.setObjectName("is_order")
        self.gridLayout.addWidget(self.is_order, 1, 5, 1, 1)
        self.verticalLayout_3.addWidget(self.editor)
        self.shower = QtWidgets.QWidget(self.new_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shower.sizePolicy().hasHeightForWidth())
        self.shower.setSizePolicy(sizePolicy)
        self.shower.setObjectName("shower")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.shower)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Path_label = QtWidgets.QLabel(self.shower)
        self.Path_label.setMinimumSize(QtCore.QSize(100, 30))
        self.Path_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.Path_label.setFont(font)
        self.Path_label.setToolTip("")
        self.Path_label.setObjectName("Path_label")
        self.verticalLayout_2.addWidget(self.Path_label)
        self.PathList = QtWidgets.QTableWidget(self.shower)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PathList.setFont(font)
        self.PathList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.PathList.setObjectName("PathList")
        self.PathList.setColumnCount(2)
        self.PathList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.PathList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PathList.setHorizontalHeaderItem(1, item)
        self.PathList.horizontalHeader().setDefaultSectionSize(150)
        self.PathList.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.PathList)
        self.verticalLayout_3.addWidget(self.shower)
        self.widget_6 = QtWidgets.QWidget(self.new_page)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.ClearButton = QtWidgets.QPushButton(self.widget_6)
        self.ClearButton.setMinimumSize(QtCore.QSize(80, 25))
        self.ClearButton.setMaximumSize(QtCore.QSize(80, 25))
        self.ClearButton.setObjectName("ClearButton")
        self.horizontalLayout_5.addWidget(self.ClearButton)
        self.StartButton = QtWidgets.QPushButton(self.widget_6)
        self.StartButton.setMinimumSize(QtCore.QSize(80, 25))
        self.StartButton.setMaximumSize(QtCore.QSize(80, 25))
        self.StartButton.setObjectName("StartButton")
        self.horizontalLayout_5.addWidget(self.StartButton)
        self.CloseButton = QtWidgets.QPushButton(self.widget_6)
        self.CloseButton.setMinimumSize(QtCore.QSize(80, 25))
        self.CloseButton.setMaximumSize(QtCore.QSize(80, 25))
        self.CloseButton.setCheckable(True)
        self.CloseButton.setAutoDefault(True)
        self.CloseButton.setObjectName("CloseButton")
        self.horizontalLayout_5.addWidget(self.CloseButton)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.tabWidget.addTab(self.new_page, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabWidgetPage2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.tabWidgetPage2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.nickname2 = QtWidgets.QLabel(self.widget_3)
        self.nickname2.setEnabled(False)
        self.nickname2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.nickname2.setFont(font)
        self.nickname2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nickname2.setTextFormat(QtCore.Qt.AutoText)
        self.nickname2.setIndent(10)
        self.nickname2.setObjectName("nickname2")
        self.horizontalLayout_4.addWidget(self.nickname2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.his_num = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(11)
        self.his_num.setFont(font)
        self.his_num.setAlignment(QtCore.Qt.AlignCenter)
        self.his_num.setObjectName("his_num")
        self.horizontalLayout_4.addWidget(self.his_num)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.history = QtWidgets.QTableWidget(self.tabWidgetPage2)
        self.history.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.history.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.history.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.history.setGridStyle(QtCore.Qt.DashLine)
        self.history.setObjectName("history")
        self.history.setColumnCount(6)
        self.history.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.history.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.history.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.history.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.history.setHorizontalHeaderItem(5, item)
        self.history.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.history)
        self.widget_4 = QtWidgets.QWidget(self.tabWidgetPage2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.check_btn = QtWidgets.QPushButton(self.widget_4)
        self.check_btn.setMinimumSize(QtCore.QSize(80, 25))
        self.check_btn.setMaximumSize(QtCore.QSize(80, 25))
        self.check_btn.setObjectName("check_btn")
        self.horizontalLayout_6.addWidget(self.check_btn)
        self.logout_btn = QtWidgets.QPushButton(self.widget_4)
        self.logout_btn.setMinimumSize(QtCore.QSize(80, 25))
        self.logout_btn.setMaximumSize(QtCore.QSize(80, 25))
        self.logout_btn.setObjectName("logout_btn")
        self.horizontalLayout_6.addWidget(self.logout_btn)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 14)
        TravelMainWindow.setCentralWidget(self.Centralwidget)
        self.Statusbar = QtWidgets.QStatusBar(TravelMainWindow)
        self.Statusbar.setObjectName("Statusbar")
        TravelMainWindow.setStatusBar(self.Statusbar)

        self.retranslateUi(TravelMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TravelMainWindow)

    def retranslateUi(self, TravelMainWindow):
        _translate = QtCore.QCoreApplication.translate
        TravelMainWindow.setWindowTitle(_translate("TravelMainWindow", "旅行模拟器"))
        self.TitleLabel.setText(_translate("TravelMainWindow", "旅行模拟系统"))
        self.nickname1.setText(_translate("TravelMainWindow", "旅客1"))
        self.label_2.setText(_translate("TravelMainWindow", "出发时间："))
        self.label_4.setText(_translate("TravelMainWindow", "天"))
        self.label_3.setText(_translate("TravelMainWindow", "小时后"))
        self.groupBox.setTitle(_translate("TravelMainWindow", "请先选择模拟策略"))
        self.bullet.setText(_translate("TravelMainWindow", "高铁动车优先"))
        self.train.setText(_translate("TravelMainWindow", "绿皮火车优先"))
        self.best_time.setText(_translate("TravelMainWindow", "旅程最短"))
        self.best_price.setText(_translate("TravelMainWindow", "旅费最省"))
        self.confirm_btn.setText(_translate("TravelMainWindow", "确认"))
        self.three.setText(_translate("TravelMainWindow", "限时最少开销"))
        self.air.setText(_translate("TravelMainWindow", "航班优先"))
        self.time_lab.setText(_translate("TravelMainWindow", "本段时限（小时）"))
        self.TBox.setItemText(0, _translate("TravelMainWindow", "不停留"))
        self.TBox.setItemText(1, _translate("TravelMainWindow", "2小时"))
        self.TBox.setItemText(2, _translate("TravelMainWindow", "4小时"))
        self.TBox.setItemText(3, _translate("TravelMainWindow", "8小时"))
        self.TBox.setItemText(4, _translate("TravelMainWindow", "12小时"))
        self.TBox.setItemText(5, _translate("TravelMainWindow", "18小时"))
        self.TBox.setItemText(6, _translate("TravelMainWindow", "一天"))
        self.TBox.setItemText(7, _translate("TravelMainWindow", "两天"))
        self.TBox.setItemText(8, _translate("TravelMainWindow", "三天"))
        self.TBox.setItemText(9, _translate("TravelMainWindow", "一周"))
        self.SBox.setItemText(0, _translate("TravelMainWindow", "北京"))
        self.SBox.setItemText(1, _translate("TravelMainWindow", "上海"))
        self.SBox.setItemText(2, _translate("TravelMainWindow", "天津"))
        self.SBox.setItemText(3, _translate("TravelMainWindow", "重庆"))
        self.SBox.setItemText(4, _translate("TravelMainWindow", "石家庄"))
        self.SBox.setItemText(5, _translate("TravelMainWindow", "太原"))
        self.SBox.setItemText(6, _translate("TravelMainWindow", "沈阳"))
        self.SBox.setItemText(7, _translate("TravelMainWindow", "长春"))
        self.SBox.setItemText(8, _translate("TravelMainWindow", "哈尔滨"))
        self.SBox.setItemText(9, _translate("TravelMainWindow", "南京"))
        self.SBox.setItemText(10, _translate("TravelMainWindow", "杭州"))
        self.SBox.setItemText(11, _translate("TravelMainWindow", "合肥"))
        self.SBox.setItemText(12, _translate("TravelMainWindow", "福州"))
        self.SBox.setItemText(13, _translate("TravelMainWindow", "南昌"))
        self.SBox.setItemText(14, _translate("TravelMainWindow", "济南"))
        self.SBox.setItemText(15, _translate("TravelMainWindow", "郑州"))
        self.SBox.setItemText(16, _translate("TravelMainWindow", "广州"))
        self.SBox.setItemText(17, _translate("TravelMainWindow", "长沙"))
        self.SBox.setItemText(18, _translate("TravelMainWindow", "武汉"))
        self.SBox.setItemText(19, _translate("TravelMainWindow", "海口"))
        self.SBox.setItemText(20, _translate("TravelMainWindow", "成都"))
        self.SBox.setItemText(21, _translate("TravelMainWindow", "贵阳"))
        self.SBox.setItemText(22, _translate("TravelMainWindow", "昆明"))
        self.SBox.setItemText(23, _translate("TravelMainWindow", "西安"))
        self.SBox.setItemText(24, _translate("TravelMainWindow", "兰州"))
        self.SBox.setItemText(25, _translate("TravelMainWindow", "西宁"))
        self.SBox.setItemText(26, _translate("TravelMainWindow", "呼和浩特"))
        self.SBox.setItemText(27, _translate("TravelMainWindow", "南宁"))
        self.SBox.setItemText(28, _translate("TravelMainWindow", "拉萨"))
        self.SBox.setItemText(29, _translate("TravelMainWindow", "银川"))
        self.SBox.setItemText(30, _translate("TravelMainWindow", "乌鲁木齐"))
        self.Add_btn.setText(_translate("TravelMainWindow", "添加路径"))
        self.label.setText(_translate("TravelMainWindow", "逗留时间"))
        self.Start.setText(_translate("TravelMainWindow", "始发地"))
        self.PBox.setItemText(0, _translate("TravelMainWindow", "北京"))
        self.PBox.setItemText(1, _translate("TravelMainWindow", "上海"))
        self.PBox.setItemText(2, _translate("TravelMainWindow", "天津"))
        self.PBox.setItemText(3, _translate("TravelMainWindow", "重庆"))
        self.PBox.setItemText(4, _translate("TravelMainWindow", "石家庄"))
        self.PBox.setItemText(5, _translate("TravelMainWindow", "太原"))
        self.PBox.setItemText(6, _translate("TravelMainWindow", "沈阳"))
        self.PBox.setItemText(7, _translate("TravelMainWindow", "长春"))
        self.PBox.setItemText(8, _translate("TravelMainWindow", "哈尔滨"))
        self.PBox.setItemText(9, _translate("TravelMainWindow", "南京"))
        self.PBox.setItemText(10, _translate("TravelMainWindow", "杭州"))
        self.PBox.setItemText(11, _translate("TravelMainWindow", "合肥"))
        self.PBox.setItemText(12, _translate("TravelMainWindow", "福州"))
        self.PBox.setItemText(13, _translate("TravelMainWindow", "南昌"))
        self.PBox.setItemText(14, _translate("TravelMainWindow", "济南"))
        self.PBox.setItemText(15, _translate("TravelMainWindow", "郑州"))
        self.PBox.setItemText(16, _translate("TravelMainWindow", "广州"))
        self.PBox.setItemText(17, _translate("TravelMainWindow", "长沙"))
        self.PBox.setItemText(18, _translate("TravelMainWindow", "武汉"))
        self.PBox.setItemText(19, _translate("TravelMainWindow", "海口"))
        self.PBox.setItemText(20, _translate("TravelMainWindow", "成都"))
        self.PBox.setItemText(21, _translate("TravelMainWindow", "贵阳"))
        self.PBox.setItemText(22, _translate("TravelMainWindow", "昆明"))
        self.PBox.setItemText(23, _translate("TravelMainWindow", "西安"))
        self.PBox.setItemText(24, _translate("TravelMainWindow", "兰州"))
        self.PBox.setItemText(25, _translate("TravelMainWindow", "西宁"))
        self.PBox.setItemText(26, _translate("TravelMainWindow", "呼和浩特"))
        self.PBox.setItemText(27, _translate("TravelMainWindow", "南宁"))
        self.PBox.setItemText(28, _translate("TravelMainWindow", "拉萨"))
        self.PBox.setItemText(29, _translate("TravelMainWindow", "银川"))
        self.PBox.setItemText(30, _translate("TravelMainWindow", "乌鲁木齐"))
        self.is_order.setText(_translate("TravelMainWindow", "是否有序"))
        self.Path_label.setText(_translate("TravelMainWindow", "路径"))
        item = self.PathList.horizontalHeaderItem(0)
        item.setText(_translate("TravelMainWindow", "旅途"))
        item = self.PathList.horizontalHeaderItem(1)
        item.setText(_translate("TravelMainWindow", "预计最短逗留时间"))
        self.ClearButton.setText(_translate("TravelMainWindow", "清空"))
        self.StartButton.setText(_translate("TravelMainWindow", "开始"))
        self.CloseButton.setText(_translate("TravelMainWindow", "退出"))
        self.nickname2.setText(_translate("TravelMainWindow", "旅客1"))
        self.label_6.setText(_translate("TravelMainWindow", "共"))
        self.his_num.setText(_translate("TravelMainWindow", "0"))
        self.label_8.setText(_translate("TravelMainWindow", "条数据"))
        item = self.history.horizontalHeaderItem(0)
        item.setText(_translate("TravelMainWindow", "起点"))
        item = self.history.horizontalHeaderItem(1)
        item.setText(_translate("TravelMainWindow", "最早出发时间"))
        item = self.history.horizontalHeaderItem(2)
        item.setText(_translate("TravelMainWindow", "交通偏好"))
        item = self.history.horizontalHeaderItem(3)
        item.setText(_translate("TravelMainWindow", "旅行策略"))
        item = self.history.horizontalHeaderItem(4)
        item.setText(_translate("TravelMainWindow", "终点"))
        item = self.history.horizontalHeaderItem(5)
        item.setText(_translate("TravelMainWindow", "储存日期"))
        self.check_btn.setText(_translate("TravelMainWindow", "查看"))
        self.logout_btn.setText(_translate("TravelMainWindow", "登出"))

