# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schedule_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScheduleWindow(object):
    def setupUi(self, ScheduleWindow):
        ScheduleWindow.setObjectName("ScheduleWindow")
        ScheduleWindow.resize(1600, 1002)
        self.verticalLayout = QtWidgets.QVBoxLayout(ScheduleWindow)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_widget = QtWidgets.QWidget(ScheduleWindow)
        self.title_widget.setMinimumSize(QtCore.QSize(0, 60))
        self.title_widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.title_widget.setObjectName("title_widget")
        self.TitleLayout = QtWidgets.QHBoxLayout(self.title_widget)
        self.TitleLayout.setObjectName("TitleLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TitleLayout.addItem(spacerItem)
        self.Title = QtWidgets.QLabel(self.title_widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.TitleLayout.addWidget(self.Title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TitleLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.title_widget)
        self.stackedWidget = QtWidgets.QStackedWidget(ScheduleWindow)
        self.stackedWidget.setObjectName("stackedWidget")
        self.list_page = QtWidgets.QWidget()
        self.list_page.setObjectName("list_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.list_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.list_page)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SubTitle = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SubTitle.setFont(font)
        self.SubTitle.setObjectName("SubTitle")
        self.horizontalLayout.addWidget(self.SubTitle)
        self.verticalLayout_2.addWidget(self.widget)
        self.BottomLayer = QtWidgets.QHBoxLayout()
        self.BottomLayer.setContentsMargins(-1, -1, 20, -1)
        self.BottomLayer.setObjectName("BottomLayer")
        self.save_btn = QtWidgets.QPushButton(self.list_page)
        self.save_btn.setMinimumSize(QtCore.QSize(100, 25))
        self.save_btn.setMaximumSize(QtCore.QSize(100, 25))
        self.save_btn.setObjectName("save_btn")
        self.BottomLayer.addWidget(self.save_btn)
        self.sim_btn = QtWidgets.QPushButton(self.list_page)
        self.sim_btn.setMinimumSize(QtCore.QSize(100, 25))
        self.sim_btn.setMaximumSize(QtCore.QSize(100, 25))
        self.sim_btn.setObjectName("sim_btn")
        self.BottomLayer.addWidget(self.sim_btn)
        self.CloseButton = QtWidgets.QPushButton(self.list_page)
        self.CloseButton.setMinimumSize(QtCore.QSize(100, 25))
        self.CloseButton.setMaximumSize(QtCore.QSize(100, 25))
        self.CloseButton.setObjectName("CloseButton")
        self.BottomLayer.addWidget(self.CloseButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.BottomLayer.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.BottomLayer)
        self.ScheduleTable = QtWidgets.QTableWidget(self.list_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ScheduleTable.setFont(font)
        self.ScheduleTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ScheduleTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ScheduleTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.ScheduleTable.setGridStyle(QtCore.Qt.DashLine)
        self.ScheduleTable.setObjectName("ScheduleTable")
        self.ScheduleTable.setColumnCount(11)
        self.ScheduleTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ScheduleTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ScheduleTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ScheduleTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ScheduleTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ScheduleTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ScheduleTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ScheduleTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ScheduleTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.ScheduleTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.ScheduleTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.ScheduleTable.setHorizontalHeaderItem(10, item)
        self.ScheduleTable.horizontalHeader().setDefaultSectionSize(140)
        self.verticalLayout_2.addWidget(self.ScheduleTable)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(2, 12)
        self.stackedWidget.addWidget(self.list_page)
        self.map_page = QtWidgets.QWidget()
        self.map_page.setObjectName("map_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.map_page)
        self.verticalLayout_4.setContentsMargins(15, 0, 15, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_5 = QtWidgets.QWidget(self.map_page)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.progress = QtWidgets.QSlider(self.widget_5)
        self.progress.setProperty("value", 30)
        self.progress.setOrientation(QtCore.Qt.Horizontal)
        self.progress.setObjectName("progress")
        self.horizontalLayout_5.addWidget(self.progress)
        self.start_btn = QtWidgets.QPushButton(self.widget_5)
        self.start_btn.setMinimumSize(QtCore.QSize(80, 30))
        self.start_btn.setMaximumSize(QtCore.QSize(100, 30))
        self.start_btn.setCheckable(True)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_5.addWidget(self.start_btn)
        self.speed_btn = QtWidgets.QPushButton(self.widget_5)
        self.speed_btn.setMinimumSize(QtCore.QSize(80, 30))
        self.speed_btn.setMaximumSize(QtCore.QSize(80, 30))
        self.speed_btn.setCheckable(True)
        self.speed_btn.setObjectName("speed_btn")
        self.horizontalLayout_5.addWidget(self.speed_btn)
        self.back_btn = QtWidgets.QPushButton(self.widget_5)
        self.back_btn.setMinimumSize(QtCore.QSize(165, 30))
        self.back_btn.setMaximumSize(QtCore.QSize(165, 30))
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_5.addWidget(self.back_btn)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.widget_2 = QtWidgets.QWidget(self.map_page)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.map = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map.sizePolicy().hasHeightForWidth())
        self.map.setSizePolicy(sizePolicy)
        self.map.setMinimumSize(QtCore.QSize(1350, 900))
        self.map.setMaximumSize(QtCore.QSize(1350, 900))
        self.map.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.map.setText("")
        self.map.setPixmap(QtGui.QPixmap(":/map/China.png"))
        self.map.setObjectName("map")
        self.horizontalLayout_7.addWidget(self.map)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.date = QtWidgets.QLabel(self.widget_4)
        self.date.setMinimumSize(QtCore.QSize(0, 30))
        self.date.setMaximumSize(QtCore.QSize(16777215, 30))
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.verticalLayout_3.addWidget(self.date)
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_7)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.day = QtWidgets.QLabel(self.widget_7)
        self.day.setObjectName("day")
        self.horizontalLayout_2.addWidget(self.day)
        self.time = QtWidgets.QLabel(self.widget_7)
        self.time.setObjectName("time")
        self.horizontalLayout_2.addWidget(self.time)
        self.verticalLayout_3.addWidget(self.widget_7)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.state = QtWidgets.QLabel(self.widget_3)
        self.state.setAlignment(QtCore.Qt.AlignCenter)
        self.state.setObjectName("state")
        self.horizontalLayout_6.addWidget(self.state)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_8 = QtWidgets.QWidget(self.widget_4)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.method = QtWidgets.QLabel(self.widget_8)
        self.method.setAlignment(QtCore.Qt.AlignCenter)
        self.method.setObjectName("method")
        self.horizontalLayout_3.addWidget(self.method)
        self.code = QtWidgets.QLabel(self.widget_8)
        self.code.setAlignment(QtCore.Qt.AlignCenter)
        self.code.setObjectName("code")
        self.horizontalLayout_3.addWidget(self.code)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.widget_4)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.posi = QtWidgets.QLabel(self.widget_9)
        self.posi.setAlignment(QtCore.Qt.AlignCenter)
        self.posi.setObjectName("posi")
        self.horizontalLayout_4.addWidget(self.posi)
        self.verticalLayout_3.addWidget(self.widget_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 735, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_7.addWidget(self.widget_4)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.stackedWidget.addWidget(self.map_page)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(ScheduleWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ScheduleWindow)

    def retranslateUi(self, ScheduleWindow):
        _translate = QtCore.QCoreApplication.translate
        ScheduleWindow.setWindowTitle(_translate("ScheduleWindow", "旅行模拟器"))
        self.Title.setText(_translate("ScheduleWindow", "旅行模拟系统"))
        self.SubTitle.setText(_translate("ScheduleWindow", "参考计划如下"))
        self.save_btn.setText(_translate("ScheduleWindow", "保存"))
        self.sim_btn.setText(_translate("ScheduleWindow", "添加模拟"))
        self.CloseButton.setText(_translate("ScheduleWindow", "关闭"))
        item = self.ScheduleTable.horizontalHeaderItem(0)
        item.setText(_translate("ScheduleWindow", "出发日期"))
        item = self.ScheduleTable.horizontalHeaderItem(1)
        item.setText(_translate("ScheduleWindow", "出发时间"))
        item = self.ScheduleTable.horizontalHeaderItem(2)
        item.setText(_translate("ScheduleWindow", "交通方式"))
        item = self.ScheduleTable.horizontalHeaderItem(3)
        item.setText(_translate("ScheduleWindow", "班次"))
        item = self.ScheduleTable.horizontalHeaderItem(4)
        item.setText(_translate("ScheduleWindow", "始发地"))
        item = self.ScheduleTable.horizontalHeaderItem(5)
        item.setText(_translate("ScheduleWindow", "终到地"))
        item = self.ScheduleTable.horizontalHeaderItem(6)
        item.setText(_translate("ScheduleWindow", "耗时"))
        item = self.ScheduleTable.horizontalHeaderItem(7)
        item.setText(_translate("ScheduleWindow", "到达日期"))
        item = self.ScheduleTable.horizontalHeaderItem(8)
        item.setText(_translate("ScheduleWindow", "到达时间"))
        item = self.ScheduleTable.horizontalHeaderItem(9)
        item.setText(_translate("ScheduleWindow", "状态"))
        item = self.ScheduleTable.horizontalHeaderItem(10)
        item.setText(_translate("ScheduleWindow", "票价"))
        self.start_btn.setText(_translate("ScheduleWindow", "开始/暂停"))
        self.speed_btn.setText(_translate("ScheduleWindow", "加速/正常"))
        self.back_btn.setText(_translate("ScheduleWindow", "返回"))
        self.date.setText(_translate("ScheduleWindow", "TextLabel"))
        self.label.setText(_translate("ScheduleWindow", "DAY"))
        self.day.setText(_translate("ScheduleWindow", "1"))
        self.time.setText(_translate("ScheduleWindow", "12:00"))
        self.state.setText(_translate("ScheduleWindow", "经停 准备出发"))
        self.method.setText(_translate("ScheduleWindow", "高铁动车"))
        self.code.setText(_translate("ScheduleWindow", "G12"))
        self.posi.setText(_translate("ScheduleWindow", "北京 至 石家庄"))

import schedue_rc
